version: '{build}'
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore src\AwesomeProxy.sln
build:
  project: src/AwesomeProxy.sln
artifacts:
- path: .\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.nuget.org/packages/AwesomeProxy.Net/
  api_key:
    secure: FT9UUgylw6RFOKsRjSKH5M3Uv9H+kyzigWqoR/OQYvH6XU9fIwn7nWYAdZo4cjtX
  skip_symbols: false
  on:
    branch: master