version: 1.0.'{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: Any CPU
shallow_clone: true
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore src\AwesomeProxy.sln
build:
  project: src/AwesomeProxy.sln
  publish_azure_webjob: true
  verbosity: minimal
artifacts:
- path: .\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://api.nuget.org/v3/index.json
  api_key:
    secure: N8XhMwrR9A+0U9zzYYMOWF3xzD1miiu824syuaN1ovk=
  skip_symbols: false
  artifact: .\*.nupkg
  on:
    branch: master
