version: '{build}'
branches:
  only:
  - master
platform: Any CPU
build:
  project: src/AwesomeProxy.sln
  verbosity: minimal
test:
  # only assemblies to test
  assemblies:
    only:
      - 'src\bin\**\*.tests.dll'
artifacts:
 - path: .\artifacts\**\*.nupkg
   name: NuGet
deploy:
  - provider: NuGet
    name: production
    server: 
    api_key:
      secure: dVGhZLkMStsaLyTFEWcfEuMmgm9z4FfsV9+yK+Fpr7E+1oC5wjkqK31qhQI5FpxZ
    skip_symbols: true
    on:
      branch: master
# For PRs, skip the branch run and only run against the virtual PR merge.
skip_branch_with_pr: true